// ignore_for_file: unnecessary_string_escapes

import 'package:insomnia_app/Constants/app_styles.dart';
import 'package:insomnia_app/Models/stories_model.dart';

class StoriesRepository {
  List<StoryModel> stories = [
    StoryModel(
      title: "Midnight Adventures in the Enchanted Forest",
      description:
          "Once upon a time, in a magical forest nestled between towering trees and glistening streams, there lived a curious little fox named Finn. Finn was known throughout the forest for his adventurous spirit and his insatiable curiosity about the world around him.One evening, as the sun dipped below the horizon and painted the sky with hues of orange and pink, Finn found himself unable to sleep. Restless and wide awake, he decided to embark on a nighttime adventure to discover the secrets of the forest under the moonlit sky.With soft pawsteps, Finn ventured deeper into the forest, guided by the gentle glow of the moon above. He tiptoed past sleeping owls and silent rabbits, his ears perked up to catch the whispers of the night.As he wandered through the enchanted forest, Finn stumbled upon a sparkling pond illuminated by the shimmering moonlight. The water danced and shimmered like liquid silver, inviting Finn to take a closer look.With a curious leap, Finn hopped onto a mossy rock by the water's edge and peered into the pond. To his amazement, he saw the reflection of a wise old owl staring back at him.\"Who are you, little fox, and what brings you to my pond on this moonlit night?\" the owl asked in a hushed voice.\"I couldn\'t sleep, so I came to explore the wonders of the night,\" Finn replied with a twinkle in his eye.The wise old owl nodded knowingly and beckoned Finn to join him by the water. Together, they sat in silence, listening to the gentle rustle of the leaves and the distant song of the crickets.As the night wore on, Finn felt his eyelids grow heavy, and a wave of drowsiness washed over him. With a contented sigh, he nestled into the soft moss by the pond and closed his eyes, lulled to sleep by the soothing sounds of the forest.And so, under the watchful gaze of the wise old owl and the twinkling stars above, Finn drifted into a peaceful slumber, dreaming of endless adventures yet to come in the magical forest that he called home.And as the night whispered its lullaby, the little fox slept soundly, wrapped in the warm embrace of the forest and the gentle embrace of the night.",
      imageUrl: AppStyles.story1,
    ),
    StoryModel(
      title: "Whispers of the Midnight Dreams",
      description:
          "In the heart of a bustling city, where tall buildings touched the sky and the streets buzzed with activity, there lived a young girl named Lily. Lily was a dreamer, with a heart full of wonder and imagination that often kept her awake long after the city lights had dimmed.One night, as Lily lay in bed staring up at the ceiling, she couldn't shake the feeling of restlessness that tugged at her mind. Despite her best efforts to drift off to sleep, her thoughts raced like shooting stars across the night sky.Determined to quiet her restless mind, Lily decided to embark on a magical journey within the realms of her own imagination. With a whispered wish and a sprinkle of stardust, she closed her eyes and let her dreams carry her away.In an instant, Lily found herself soaring through the night sky on the back of a shimmering dragon, its scales glistening like precious jewels in the moonlight. Together, they flew over towering mountains and vast oceans, weaving through the stars like threads of light.As they journeyed deeper into the night, Lily and her dragon encountered a mystical forest filled with glowing fireflies and whispering trees. They danced among the dappled shadows and shimmering moonbeams, their laughter echoing through the enchanted woods.In the heart of the forest, they stumbled upon a hidden clearing bathed in the soft glow of a thousand fireflies. In the center of the clearing stood a majestic tree with branches reaching towards the heavens, its leaves shimmering like emerald jewels.With a sense of wonder, Lily approached the tree and reached out to touch its glowing leaves. As she did, a gentle breeze swept through the clearing, carrying with it the sweet scent of wildflowers and the soft melody of a lullaby.With a contented sigh, Lily nestled into the soft grass beneath the tree and closed her eyes, letting the gentle lullaby of the night wash over her like a warm embrace. And as she drifted off to sleep, she knew that she would always carry the magic of this midnight adventure in her heart.For in the world of dreams, anything is possible, and the imagination knows no bounds. And so, with a smile on her lips and a heart full of wonder, Lily surrendered to the sweet embrace of sleep, knowing that her dreams would carry her to places beyond imagination.And as the night whispered its secrets and the stars twinkled overhead, Lily slept soundly, cradled in the arms of her own magical dreams.",
      imageUrl: AppStyles.story2,
    ),
    StoryModel(
      title: "The Moonlit Garden",
      description:
          "In a quaint village nestled between rolling hills and winding rivers, there lay a hidden garden known only to a few. This garden, illuminated by the soft glow of the moon each night, was said to be a place of enchantment and wonder.One evening, a young girl named Elara stumbled upon the garden as she wandered through the village in search of adventure. Intrigued by the whispers of magic that danced on the evening breeze, she ventured through the garden gates and into the moonlit sanctuary.Within the garden, Elara discovered a world teeming with life and beauty. Moonflowers bloomed in shades of silver and pearl, their petals glowing like tiny lanterns in the darkness. Fireflies danced among the branches of ancient trees, painting the air with trails of golden light.As Elara wandered deeper into the garden, she came upon a shimmering pond at the heart of the sanctuary. Its surface rippled with reflections of the stars above, casting a spellbinding spell over the tranquil waters.Mesmerized by the beauty of the garden, Elara lay down in the soft grass and gazed up at the moon above. With each breath, she felt herself drifting closer to sleep, lulled by the gentle whispers of the night.And as the moonlight bathed the garden in its ethereal glow, Elara closed her eyes and surrendered to the sweet embrace of sleep, knowing that she would return to this enchanted sanctuary in her dreams.",
      imageUrl: AppStyles.story3,
    ),
    StoryModel(
      title: "The Starlight Carousel",
      description:
          "In a faraway kingdom, hidden beyond the clouds and stars, there existed a magical carousel that spun beneath the light of a thousand twinkling stars. This carousel, crafted from stardust and dreams, was said to grant wishes to those who dared to ride its shimmering horses.One night, a young boy named Oliver discovered the carousel as he gazed up at the night sky from his bedroom window. Entranced by the sight of the glittering stars, he climbed out onto the window ledge and reached out towards the heavens.To his amazement, the stars responded to his touch, guiding him through the night sky until he reached the carousel hidden among the clouds. With a sense of wonder, Oliver climbed onto the back of one of the carousel horses and held on tight as it began to spin.As the carousel whirled beneath the canopy of stars, Oliver felt a sense of joy and exhilaration unlike anything he had ever experienced. With each revolution, he reached out towards the stars above, his heart filled with dreams and wishes.And as the night wore on and the carousel spun ever faster, Oliver closed his eyes and let himself be carried away by the magic of the moment. He knew that no matter where life took him, he would always cherish the memory of this starlit ride beneath the midnight sky.And so, as the first light of dawn painted the horizon with hues of pink and gold, Oliver returned home with a heart full of dreams and a smile upon his lips, knowing that the magic of the carousel would stay with him forever.",
      imageUrl: AppStyles.story4,
    ),
    StoryModel(
      title: "The Whispering Woods",
      description:
          "Deep within the heart of the Whispering Woods, where ancient trees stood tall and proud, there lived a young girl named Maya. Maya had always been drawn to the secrets of the forest, captivated by the gentle whispers of the wind among the leaves.One night, as the moon rose high in the sky and cast its silvery glow upon the forest floor, Maya ventured into the Whispering Woods in search of adventure. With each step, she felt the magic of the forest enveloping her like a warm embrace.As Maya wandered deeper into the woods, she stumbled upon a hidden clearing bathed in the soft light of the moon. In the center of the clearing stood a circle of ancient stones, their surfaces etched with symbols of a forgotten time.Intrigued by the sight, Maya approached the stone circle and reached out to touch the cool, smooth surface of one of the stones. To her amazement, she felt a gentle vibration beneath her fingertips, as if the stones themselves were alive with energy.As she stood among the stones, Maya closed her eyes and listened to the whispers of the forest around her. She heard the soft rustle of leaves, the gentle murmur of a distant stream, and the faint call of a nightingale in the trees.With each passing moment, Maya felt herself growing drowsy, lulled by the soothing symphony of the Whispering Woods. And as she nestled into the soft moss beneath the ancient stones, she let the gentle lullaby of the forest carry her off to sleep.And so, under the watchful gaze of the moon and the stars above, Maya drifted into a peaceful slumber, dreaming of endless adventures among the whispering trees. And as the night whispered its secrets and the forest embraced her in its gentle embrace, Maya slept soundly, knowing that she was safe and loved in the heart of the Whispering Woods.",
      imageUrl: AppStyles.story5,
    ),
  ];
}
